#!/usr/bin/env python3
import argparse
import datetime
import json
import os
import sys

from PDFGenerator import PDFGenerator

APP_CONFIG_PATH = f"{os.environ['PROGRAMS_CONFIG_PATH']}/cvs/config"

def parse_args():
    parser = argparse.ArgumentParser(description='Generates a pdf version of a cv')

    parser.add_argument('--language', type=str, default='en', help='Language of the cv')
    parser.add_argument('--company', type=str, help='Company to whom the cv is addressed')

    args = parser.parse_args()

    return args

def read_config_variables(file):
    config_json_file = f"{APP_CONFIG_PATH}/{file}.json"

    with open(config_json_file, 'r') as config_file:
        config_vars = json.load(config_file)

    return config_vars

def generate_pdf_name(cv_data, company_name):
    now = datetime.datetime.now()
    date = now.strftime("%Y%m%d")

    company = "" if company_name is None else f" - {company_name}"

    return f"CV {cv_data['header']['name']} - {date}{company}.pdf"

args = parse_args()
pdf = PDFGenerator(APP_CONFIG_PATH, company_name=args.company, language=args.language)
pdf.generate_cv()

cv_data = pdf.get_cv_data()
pdf_name = generate_pdf_name(cv_data, args.company)

config_vars = read_config_variables('cvs')
pdf_path = f"{config_vars['output_path']}/{pdf_name}"

pdf.output(pdf_path, 'F')
